Repository GreenBlitz/FTC-CENTERSTAGE, pull requests merged in 2024-06, with the labels that each got.

#15 yoav - gamepads
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/gamepads/GamepadConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/gamepads/GamepadFunctions.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/gamepads/GamepadWrapper.java
Labels: feature creation

#13 hillel - Add road runner and meep meep
  MeepMeepTesting/.gitignore
  MeepMeepTesting/build.gradle
  MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
  TeamCode/build.gradle
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleTankDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/TwoWheelTrackingLocalizer.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/AutomaticFeedforwardTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/BackAndForth.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/DriveVelocityPIDTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/FollowerPIDTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/LocalizationTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/ManualFeedforwardTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/MaxAngularVeloTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/MaxVelocityTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/MotorDirectionDebugger.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/SplineTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/StrafeTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/StraightTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/TrackWidthTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/TrackingWheelForwardOffsetTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/TrackingWheelLateralDistanceTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/TurnTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/EmptySequenceException.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/TrajectorySequence.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/TrajectorySequenceBuilder.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/TrajectorySequenceRunner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/sequencesegment/SequenceSegment.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/sequencesegment/TrajectorySegment.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/sequencesegment/TurnSegment.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/trajectorysequence/sequencesegment/WaitSegment.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/AssetsTrajectoryManager.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/AxesSigns.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/AxisDirection.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/BNO055IMUUtil.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/DashboardUtil.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/Encoder.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/LoggingUtil.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/LynxModuleUtil.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/util/RegressionUtil.java
  build.dependencies.gradle
  settings.gradle
Labels: feature creation

#7 yoav - Arm
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/gamepads/GamepadFunctions.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazArmTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/Arm.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmState.java
Labels: Passed All Tests, feature creation

#16 Gil - new launcher
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/DefaultRaz.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazLauncherTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/launcher/Launcher.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/launcher/LauncherCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/launcher/LauncherConstants.java
Labels: Passed All Tests, feature creation

#2 hilel - Mecanum
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/tests/RazDriveTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleTankDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/DriveVelocityPIDTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/ChassisCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/ChassisConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/MecanumChassis.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Needs Testing, feature creation

#8 danna - Wrist
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazWristTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristState.java
Labels: Passed All Tests, feature creation

#17 yoav - Calib
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
Labels: Passed All Tests, bug fix

#18 yoav - Reset system solution
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/Arm.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/Elevator.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
Labels: Needs CR, Passed All Tests, bug fix

#20 yoav - Robot State
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotState.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StateCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/robotstatetesters/RazRobotStateTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazArmTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazChassisTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazClawTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazElevatorTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazLauncherTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/subsystemstesters/RazWristTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/arm/ArmState.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/Elevator.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorState.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristState.java
Labels: Needs Testing, Needs CR, feature creation

#19 Yoav - Auto align
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/gamelayout/FieldConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/ChassisCommands.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/ChassisConstants.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/chassis/MecanumChassis.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/Elevator.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systemcontrol/ControlMode.java
Labels: Needs CR, Passed All Tests, feature creation

#26 yoav - Bindings
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StateMotionPlanner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/teleop/Duo.java
Labels: Passed All Tests, feature creation
